include_recipe 'chef-rack_stack::users'
include_recipe 'chef-rack_stack::postgres'
include_recipe 'chef-rack_stack::rails'
include_recipe 'chef-rack_stack::imagemagick'
include_recipe 'chef-rack_stack::apache_reverse_proxy'
