default['postgresql']['password']['postgres']  = 'password'
default['chef-rack_stack']['rails']['environment'] = 'production'
default['chef-rack_stack']['deploy']['user'] = 'neo_deploy'
default['chef-rack_stack']['deploy']['group'] = 'neo_deploy'
normal['passenger']['version'] = '3.0.18'
normal['languages']['ruby']['default_version'] = '1.9.1'
normal['languages']['ruby']['gems_dir'] = '/var/lib/gems/1.9.1'
normal['languages']['ruby']['ruby_bin'] = '/usr/bin/ruby'
